version: "3.7"
services:
  throwmoney_database:
    container_name: throwmoney_database
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: kakao_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
    - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  redis:
    container_name: throwmoney_redis
    image: bitnami/redis:latest
    ports:
      - 11211:11211
    environment:
      - REDIS_PASSWORD=password123

  throw-money:
    container_name: throw-money-application
    build: .
    volumes:
    - ../throw-money/:/throw-money
    command: ./gradlew bootRun
    ports:
      - 8080:8080
    depends_on:
      - throwmoney_database
      - redis