server:
  port: 8080

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    url: jdbc:mysql://throwmoney_database:3306/kakao_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 11211
    password: password123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
    host: redis





