server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  profiles:
    active: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/kakao_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    password: password123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
    host: localhost
  jwt:
    secret: 9AA89





